/**
 * Created by Jabito on 27/02/2018.
 */
export var flags = {
    "Afrikaans": "za", "Irish": "ie",
    "Albanian": "al", "Italian": "it",
    "Arabic": "eh", "Japanese": "jp",
    "Azerbaijani": "az", "Kannada": "kn",
    "Basque": "bs", "Korean": "kr",
    "Bengali": "bd", "Latin": "la",
    "Belarusian": "by", "Latvian": "lv",
    "Bulgarian": "bg", "Lithuanian": "lt",
    "Catalan": "ct", "Macedonian": "mk",
    "Chinese": "cn", "Malay": "ml",
    "Amharic": "ah", "Maltese": "mt",
    "Croatian": "hr", "Norwegian": "no",
    "Czech": "cz", "Persian": "ir",
    "Danish": "dk", "Polish": "pl",
    "Dutch": "nl", "Portuguese": "pt",
    "Romanian": "ro",
    "Russian": "ru",
    "Estonian": "et", "Serbian": "rs",
    "Filipino": "ph", "Slovak": "sk",
    "Finnish": "fi", "Slovenian": "si",
    "French": "fr", "Spanish": "es",
    "Galician": "gl", "Swahili": "ke",
    "Georgian": "ge", "Swedish": "se",
    "German": "de", "Tamil": "lk",
    "Greek": "gr", "Telugu": "te",
    "Gujarati": "gj", "Thai": "th",
    "Haitian Creole": "ht", "Turkish": "tr",
    "Hebrew": "il", "Ukrainian": "ua",
    "Hindi": "in", "Urdu": "pk",
    "Hungarian": "hu", "Vietnamese": "vn",
    "Icelandic": "is", "Welsh": "gb-wls",
    "Indonesian": "id", "Yiddish": "yd"
};

export var languages = {
    "Afrikaans": "af", "Irish": "ga",
    "Albanian": "sq", "Italian": "it",
    "Arabic": "ar", "Japanese": "ja",
    "Azerbaijani": "az", "Kannada": "kn",
    "Basque": "eu", "Korean": "ko",
    "Bengali": "bn", "Latin": "la",
    "Belarusian": "be", "Latvian": "lv",
    "Bulgarian": "bg", "Lithuanian": "lt",
    "Catalan": "ca", "Macedonian": "mk",
    "Chinese": "zh", "Malay": "ms",
    "Amharic": "am", "Maltese": "mt",
    "Croatian": "hr", "Norwegian": "no",
    "Czech": "cs", "Persian": "fa",
    "Danish": "da", "Polish": "pl",
    "Dutch": "nl", "Portuguese": "pt",
    "Romanian": "ro",
    "Russian": "ru",
    "Estonian": "et", "Serbian": "sr",
    "Filipino": "tl", "Slovak": "sk",
    "Finnish": "fi", "Slovenian": "sl",
    "French": "fr", "Spanish": "es",
    "Galician": "gl", "Swahili": "sw",
    "Georgian": "ka", "Swedish": "sv",
    "German": "de", "Tamil": "ta",
    "Greek": "el", "Telugu": "te",
    "Gujarati": "gu", "Thai": "th",
    "Haitian Creole": "ht", "Turkish": "tr",
    "Hebrew": "iw", "Ukrainian": "uk",
    "Hindi": "hi", "Urdu": "ur",
    "Hungarian": "hu", "Vietnamese": "vi",
    "Icelandic": "is", "Welsh": "cy",
    "Indonesian": "id", "Yiddish": "yi"
};
