/**
 * Created by Jabito on 27/02/2018.
 */
export var flags = {
    "Afrikaans": "za",  "Albanian": "al", 
    "Italian": "it", "Arabic": "eh", 
    "Basque": "bs", "Korean": "kr",
    "Bengali": "bd", "Belarusian": "by", 
    "Latvian": "lv", "Bulgarian": "bg", 
    "Lithuanian": "lt", "Chinese": "cn", 
    "Croatian": "hr", "Norwegian": "no",
    "Czech": "cz", "Persian": "ir",
    "Danish": "dk", "Polish": "pl",
    "Dutch": "nl", "Portuguese": "pt",
    "Romanian": "ro", "Russian": "ru",
    "Estonian": "et", "Serbian": "rs",
    "Filipino": "ph", "Slovak": "sk",
    "Finnish": "fi", "Slovenian": "si",
    "French": "fr", "Spanish": "es",
    "Galician": "gl", "Swahili": "ke",
    "Georgian": "ge", "Swedish": "se",
    "German": "de", "Greek": "gr", 
    "Telugu": "te",  "Thai": "th",
    "Turkish": "tr", "Amharic": "ah", 
    "Hebrew": "il", "Ukrainian": "ua",
    "Hindi": "in", "Urdu": "pk",
    "Hungarian": "hu", "Vietnamese": "vn"
};

export var languages = {
    "Afrikaans": "af", "Albanian": "sq", 
     "Italian": "it",  "Arabic": "ar", 
     "Basque": "eu", "Korean": "ko",
     "Bengali": "bn",  "Belarusian": "be", 
     "Latvian": "lv", "Bulgarian": "bg", 
     "Lithuanian": "lt",  "Chinese": "zh", 
     "Croatian": "hr", "Norwegian": "no",
     "Czech": "cs", "Persian": "fa",
     "Danish": "da", "Polish": "pl",
     "Dutch": "nl", "Portuguese": "pt",
     "Romanian": "ro", "Russian": "ru",
     "Estonian": "et", "Serbian": "sr",
     "Filipino": "tl", "Slovak": "sk",
     "Finnish": "fi", "Slovenian": "sl",
     "French": "fr", "Spanish": "es",
     "Galician": "gl", "Swahili": "sw",
     "Georgian": "ka", "Swedish": "sv",
     "German": "de",  "Greek": "el", 
     "Telugu": "te",  "Thai": "th",
     "Turkish": "tr", "Amharic": "am",
     "Hebrew": "iw", "Ukrainian": "uk",
     "Hindi": "hi", "Urdu": "ur",
     "Hungarian": "hu", "Vietnamese": "vi",
};
